/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardComponent: typeof import('./src/components/intro/CardComponent.vue')['default']
    EditorComponent: typeof import('./src/components/editor/editorComponent.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FollowUserCardComponent: typeof import('./src/components/user/followUserCardComponent.vue')['default']
    LoginComponent: typeof import('./src/components/intro/LoginComponent.vue')['default']
    ModelCardComponent: typeof import('./src/components/rvcModel/modelCardComponent.vue')['default']
    NoticeBoardComponent: typeof import('./src/components/intro/NoticeBoardComponent.vue')['default']
    PostCardComponent: typeof import('./src/components/modelCommunication/postCardComponent.vue')['default']
    RegisterComponent: typeof import('./src/components/intro/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagSelectComponent: typeof import('./src/components/common/tagSelectComponent.vue')['default']
    WaterFallComponent: typeof import('./src/components/layout/waterFallComponent.vue')['default']
    Welcome: typeof import('./src/components/intro/welcome.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
